[package]
name = "rust-ranked-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
rocket = { version = "0.5.0", features = ["json"]}